import { buildAcknowledgmentReply, SAMPLE_SMS_PREFIX } from "@/lib/sms-grievance/auto-response";
import type { SmsMockScenario } from "@/types/sms-grievance.types";

// Realistic-feeling sample content (natural SMS phrasing, plausible PH barangay/project
// names) so this reads like a real grievance queue during a walkthrough — never actual
// citizen data. Truthfulness still rests on the persistent "SMS Grievance prototype" /
// "No SMS service is connected" banner shown on every page that renders these records,
// not on marking every individual field with a "[SAMPLE]" tag.
const MASKED_CONTACT = "09*******89" as const;
const SAMPLE_RECEIVED_AT = "2026-09-19T08:00:00.000Z";

// InfraWatch covers AMEFIP (AMEFSS equipment/facilities + INS irrigation systems) — farm-
// to-market roads are FMR Watch's scope, not this app's, so sample projects stay within
// AMEFSS/INS categories (irrigation, drying/storage facilities, farm machinery, etc.).
const IRRIGATION_PUMP_PROJECT = {
  projectLabel: "Solar-Powered Irrigation Pump Installation, Brgy. San Isidro",
  projectMatch: "confirmed" as const,
  projectId: "2026-R5-CAM-INFRA-INS-00042",
  projectCode: "2026-R5-CAM-INFRA-INS-00042",
  projectProvince: "Camarines Sur",
  projectMunicipality: "Pili",
};

function inbound(id: string, body: string) {
  return {
    id: `${id}-inbound`,
    kind: "inbound_sms" as const,
    body,
    occurredAt: SAMPLE_RECEIVED_AT,
    deliveryStatus: "not_requested" as const,
  };
}

export const SMS_MOCK_SCENARIOS: SmsMockScenario[] = [
  {
    id: "sample-sms-001",
    scenario: "anonymous_valid",
    prototype: true,
    externalMessageId: "SMS-2026-000001",
    conversationId: "sample-conversation-001",
    receivedAt: SAMPLE_RECEIVED_AT,
    originalText: "INFRAWATCH | ANONYMOUS | Brgy. San Isidro, Pili, Camarines Sur | Sira na po yung solar irrigation pump, tatlong linggo nang hindi gumagana, natutuyot na yung palayan namin",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "confirmed_in_scope",
    relevanceReason: "Names a specific barangay and an irrigation facility concern that matches an active INS project in the area.",
    status: "under_review",
    category: "irrigation_gate_valve",
    categoryLabel: "Gate, Valve, or Pump Malfunction",
    locationLabel: "Brgy. San Isidro, Pili, Camarines Sur",
    ...IRRIGATION_PUMP_PROJECT,
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "simulated_delivered",
    language: "English",
    conversation: [inbound("sample-sms-001", "INFRAWATCH | ANONYMOUS | Brgy. San Isidro, Pili, Camarines Sur | Sira na po yung solar irrigation pump, tatlong linggo nang hindi gumagana, natutuyot na yung palayan namin")],
  },
  {
    id: "sample-sms-002",
    scenario: "identified_valid",
    prototype: true,
    externalMessageId: "SMS-2026-000002",
    conversationId: "sample-conversation-002",
    receivedAt: "2026-09-19T08:05:00.000Z",
    originalText: "INFRAWATCH | Mang Ramil | Brgy. Poblacion, Guimba, Nueva Ecija | Matagal na pong tumigil yung construction ng grain dryer, mga 3 buwan na walang gumagalaw",
    contactNumber: MASKED_CONTACT,
    senderMode: "identified",
    relevance: "uncertain",
    relevanceReason: "Describes a stalled infrastructure project but the exact project record still needs staff confirmation.",
    status: "needs_relevance_review",
    category: "construction_delay",
    categoryLabel: "Construction Delay / Work Stoppage",
    locationLabel: "Brgy. Poblacion, Guimba, Nueva Ecija",
    projectLabel: "Grain Dryer and Storage Warehouse, Brgy. Poblacion (unconfirmed match)",
    projectMatch: "candidate",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "simulated_delivered",
    language: "Filipino",
    conversation: [inbound("sample-sms-002", "INFRAWATCH | Mang Ramil | Brgy. Poblacion, Guimba, Nueva Ecija | Matagal na pong tumigil yung construction ng grain dryer, mga 3 buwan na walang gumagalaw")],
  },
  {
    id: "sample-sms-003",
    scenario: "exact_project",
    prototype: true,
    externalMessageId: "SMS-2026-000003",
    conversationId: "sample-conversation-003",
    receivedAt: "2026-09-19T08:10:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Irrigation Canal Project 2026-R3-NUE-INFRA-INS-00087 | Yung semento ng canal wall, marami nang pumuputok-putok, mukhang hindi de-kalidad yung pagkakagawa",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "confirmed_in_scope",
    relevanceReason: "Cites the exact project code, which matches an irrigation project on record.",
    status: "under_review",
    category: "poor_workmanship",
    categoryLabel: "Poor Workmanship",
    locationLabel: "Brgy. Malinis, Talavera, Nueva Ecija",
    projectLabel: "Irrigation Canal Improvement, Brgy. Malinis",
    projectMatch: "confirmed",
    projectId: "2026-R3-NUE-INFRA-INS-00087",
    projectCode: "2026-R3-NUE-INFRA-INS-00087",
    projectProvince: "Nueva Ecija",
    projectMunicipality: "Talavera",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "English",
    conversation: [inbound("sample-sms-003", "INFRAWATCH | ANONYMOUS | Irrigation Canal Project 2026-R3-NUE-INFRA-INS-00087 | Yung semento ng canal wall, marami nang pumuputok-putok, mukhang hindi de-kalidad yung pagkakagawa")],
  },
  {
    id: "sample-sms-004",
    scenario: "location_only",
    prototype: true,
    externalMessageId: "SMS-2026-000004",
    conversationId: "sample-conversation-004",
    receivedAt: "2026-09-19T08:15:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Brgy. Ilog, Sta. Cruz, Laguna | Baba-baha po kami kada malakas na ulan, mababaw na yata yung drainage canal",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "uncertain",
    relevanceReason: "Names only a barangay, not a specific project — needs staff confirmation before a regional assignment.",
    status: "needs_relevance_review",
    category: "road_drainage",
    categoryLabel: "Drainage Blockage",
    locationLabel: "Brgy. Ilog, Sta. Cruz, Laguna",
    projectLabel: "Not yet identified",
    projectMatch: "not_identified",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "Regional language",
    conversation: [inbound("sample-sms-004", "INFRAWATCH | ANONYMOUS | Brgy. Ilog, Sta. Cruz, Laguna | Baba-baha po kami kada malakas na ulan, mababaw na yata yung drainage canal")],
  },
  {
    id: "sample-sms-005",
    scenario: "malformed",
    prototype: true,
    externalMessageId: "SMS-2026-000005",
    conversationId: "sample-conversation-005",
    receivedAt: "2026-09-19T08:20:00.000Z",
    originalText: "tulong po sira dito wla masyado maintindihan",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "uncertain",
    relevanceReason: "Doesn't follow the reporting template and is missing enough detail to assign — needs staff review.",
    status: "needs_relevance_review",
    category: null,
    categoryLabel: "Not yet classified",
    locationLabel: "Location not provided",
    projectLabel: "Not yet identified",
    projectMatch: "not_identified",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "English",
    conversation: [inbound("sample-sms-005", "tulong po sira dito wla masyado maintindihan")],
  },
  {
    id: "sample-sms-006",
    scenario: "unrelated",
    prototype: true,
    externalMessageId: "SMS-2026-000006",
    conversationId: "sample-conversation-006",
    receivedAt: "2026-09-19T08:25:00.000Z",
    originalText: "Pwede po ba mag-inquire dito about sa SSS pension application ko, ilang buwan na po hindi na-process",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "out_of_scope",
    relevanceReason: "Concerns an SSS pension matter, not agricultural or fisheries infrastructure.",
    status: "closed",
    category: null,
    categoryLabel: "Not for InfraWatch",
    locationLabel: "Not applicable",
    projectLabel: "Not a BAFE project",
    projectMatch: "not_bafe_project",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "Filipino",
    conversation: [inbound("sample-sms-006", "Pwede po ba mag-inquire dito about sa SSS pension application ko, ilang buwan na po hindi na-process")],
  },
  {
    id: "sample-sms-007",
    scenario: "duplicate_import",
    prototype: true,
    externalMessageId: "SMS-2026-000007",
    conversationId: "sample-conversation-007",
    duplicateOf: "sample-sms-001",
    receivedAt: "2026-09-19T08:30:00.000Z",
    originalText: "Ulit ko lang po yung report ko kanina, yung sirang solar pump sa Brgy. San Isidro, tuyong-tuyo na po yung palayan namin",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "duplicate",
    relevanceReason: "Same irrigation pump, same barangay, and same concern already reported minutes earlier as sample-sms-001.",
    status: "closed",
    category: "irrigation_gate_valve",
    categoryLabel: "Gate, Valve, or Pump Malfunction",
    locationLabel: "Brgy. San Isidro, Pili, Camarines Sur",
    projectLabel: "Not yet identified",
    projectMatch: "not_identified",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "Filipino",
    conversation: [inbound("sample-sms-007", "Ulit ko lang po yung report ko kanina, yung sirang solar pump sa Brgy. San Isidro, tuyong-tuyo na po yung palayan namin")],
  },
  {
    id: "sample-sms-008",
    scenario: "follow_up",
    prototype: true,
    externalMessageId: "SMS-2026-000008",
    conversationId: "sample-conversation-001",
    receivedAt: "2026-09-19T08:35:00.000Z",
    originalText: "Update po: mas lumala na, tuyo na rin yung kalapit na bukid, maraming apektadong magsasaka ngayon",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "confirmed_in_scope",
    relevanceReason: "Continues the same conversation as sample-sms-001 with a new impact detail.",
    status: "under_review",
    category: "irrigation_gate_valve",
    categoryLabel: "Gate, Valve, or Pump Malfunction",
    locationLabel: "Brgy. San Isidro, Pili, Camarines Sur",
    ...IRRIGATION_PUMP_PROJECT,
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "Filipino",
    conversation: [inbound("sample-sms-008", "Update po: mas lumala na, tuyo na rin yung kalapit na bukid, maraming apektadong magsasaka ngayon")],
  },
  {
    id: "sample-sms-009",
    scenario: "restricted_misconduct",
    prototype: true,
    externalMessageId: "SMS-2026-000009",
    conversationId: "sample-conversation-009",
    receivedAt: "2026-09-19T08:40:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Farm Machinery Shed, Brgy. Mabuhay | May humihingi po ng pera bago daw ma-release yung pondo, hindi po ako sigurado kung tama lang ito",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "uncertain",
    relevanceReason: "Alleges improper solicitation tied to a specific project — needs a restricted-access review before any wider handling.",
    status: "needs_relevance_review",
    category: "misconduct_corruption",
    categoryLabel: "Misconduct, improper request, or suspected corruption",
    locationLabel: "Brgy. Mabuhay, Cabanatuan, Nueva Ecija",
    projectLabel: "Farm Machinery Shed, Brgy. Mabuhay (unconfirmed match)",
    projectMatch: "candidate",
    sensitive: true,
    urgentReview: false,
    deliveryStatus: "not_requested",
    language: "Filipino",
    conversation: [inbound("sample-sms-009", "INFRAWATCH | ANONYMOUS | Farm Machinery Shed, Brgy. Mabuhay | May humihingi po ng pera bago daw ma-release yung pondo, hindi po ako sigurado kung tama lang ito")],
  },
  {
    id: "sample-sms-010",
    scenario: "possible_danger",
    prototype: true,
    externalMessageId: "SMS-2026-000010",
    conversationId: "sample-conversation-010",
    receivedAt: "2026-09-19T08:45:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Brgy. Ilaya | May malaking bitak sa dam wall ng irrigation reservoir, mukhang panganib na gumuho, may mga bahay sa ibaba nito",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "uncertain",
    relevanceReason: "Describes a possible structural hazard in progress and needs urgent staff review — this page does not notify emergency responders.",
    status: "needs_relevance_review",
    category: "safety_hazard",
    categoryLabel: "Safety Hazard",
    locationLabel: "Brgy. Ilaya, Baao, Camarines Sur",
    projectLabel: "Not yet identified",
    projectMatch: "not_identified",
    sensitive: true,
    urgentReview: true,
    deliveryStatus: "not_requested",
    language: "English",
    conversation: [inbound("sample-sms-010", "INFRAWATCH | ANONYMOUS | Brgy. Ilaya | May malaking bitak sa dam wall ng irrigation reservoir, mukhang panganib na gumuho, may mga bahay sa ibaba nito")],
  },
  {
    id: "sample-sms-011",
    scenario: "pending_acknowledgment",
    prototype: true,
    externalMessageId: "SMS-2026-000011",
    conversationId: "sample-conversation-011",
    receivedAt: "2026-09-19T08:50:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Brgy. Sto. Niño | Nakaharang pa rin yung mga construction materials sa daan, hirap na hirap dumaan ang mga sasakyan",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "confirmed_in_scope",
    relevanceReason: "Matches an active warehouse construction project already accepted as a case; acknowledgment remains simulated.",
    status: "under_review",
    category: "public_access_traffic",
    categoryLabel: "Public Access or Traffic Concern",
    locationLabel: "Brgy. Sto. Niño, Sipocot, Camarines Sur",
    projectLabel: "Warehouse and Drying Pavement Construction, Brgy. Sto. Niño",
    projectMatch: "confirmed",
    projectId: "2026-R5-CAM-INFRA-AMEFSS-00019",
    projectCode: "2026-R5-CAM-INFRA-AMEFSS-00019",
    projectProvince: "Camarines Sur",
    projectMunicipality: "Sipocot",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "simulated_pending",
    language: "Filipino",
    conversation: [inbound("sample-sms-011", "INFRAWATCH | ANONYMOUS | Brgy. Sto. Niño | Nakaharang pa rin yung mga construction materials sa daan, hirap na hirap dumaan ang mga sasakyan")],
  },
  {
    id: "sample-sms-012",
    scenario: "failed_response",
    prototype: true,
    externalMessageId: "SMS-2026-000012",
    conversationId: "sample-conversation-012",
    receivedAt: "2026-09-19T08:55:00.000Z",
    originalText: "INFRAWATCH | ANONYMOUS | Multi-Purpose Building, Brgy. Ilaya | Yung petsa ng completion na nakalagay sa project board, iba sa totoong nangyayari sa site",
    contactNumber: MASKED_CONTACT,
    senderMode: "anonymous",
    relevance: "confirmed_in_scope",
    relevanceReason: "Flags a mismatch between posted project information and site conditions; demonstrates a failed simulated reply.",
    status: "under_review",
    category: "incorrect_project_information",
    categoryLabel: "Incorrect or missing project information",
    locationLabel: "Brgy. Ilaya, Baao, Camarines Sur",
    projectLabel: "Multi-Purpose Building, Brgy. Ilaya",
    projectMatch: "confirmed",
    projectId: "2026-R5-CAM-INFRA-AMEFSS-00027",
    projectCode: "2026-R5-CAM-INFRA-AMEFSS-00027",
    projectProvince: "Camarines Sur",
    projectMunicipality: "Baao",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "simulated_failed",
    language: "English",
    conversation: [
      inbound("sample-sms-012", "INFRAWATCH | ANONYMOUS | Multi-Purpose Building, Brgy. Ilaya | Yung petsa ng completion na nakalagay sa project board, iba sa totoong nangyayari sa site"),
      {
        id: "sample-sms-012-outbound",
        kind: "outbound_sms",
        body: "SAMPLE SMS ONLY. No message was sent.",
        occurredAt: "2026-09-19T09:00:00.000Z",
        deliveryStatus: "simulated_failed",
      },
    ],
  },
  {
    id: "sample-sms-013",
    scenario: "auto_acknowledgment_demo",
    prototype: true,
    externalMessageId: "SMS-2026-000013",
    conversationId: "sample-conversation-013",
    receivedAt: "2026-09-19T09:05:00.000Z",
    originalText: "INFRAWATCH | Rey | Brgy. Malaya, Norzagaray, Bulacan | Test message lang po ito, tinetest ko lang yung SMS grievance line, wala pa namang aktwal na isyu",
    contactNumber: MASKED_CONTACT,
    senderMode: "identified",
    relevance: "uncertain",
    relevanceReason: "Staff test message used to verify the SMS grievance auto-acknowledgment. Needs review like any other message before it's tagged.",
    status: "needs_relevance_review",
    category: null,
    categoryLabel: "Not yet classified",
    locationLabel: "Brgy. Malaya, Norzagaray, Bulacan",
    projectLabel: "Not yet identified",
    projectMatch: "not_identified",
    sensitive: false,
    urgentReview: false,
    deliveryStatus: "simulated_delivered",
    language: "Filipino",
    conversation: [
      inbound("sample-sms-013", "INFRAWATCH | Rey | Brgy. Malaya, Norzagaray, Bulacan | Test message lang po ito, tinetest ko lang yung SMS grievance line, wala pa namang aktwal na isyu"),
      {
        id: "sample-sms-013-outbound-ack",
        kind: "outbound_sms",
        body: `${SAMPLE_SMS_PREFIX} ${buildAcknowledgmentReply("SMS-2026-000013")}`,
        occurredAt: "2026-09-19T09:05:05.000Z",
        deliveryStatus: "simulated_delivered",
      },
    ],
  },
];

export function getSmsMockScenario(id: string) {
  return SMS_MOCK_SCENARIOS.find((scenario) => scenario.id === id) ?? null;
}
